CC = gcc -std=c11
GCC = $(CC) -Wall -Wextra -Werror
SOURSE = main.c 
OBJECT =

debug:
	$(CC) $(SOURSE)

all: 

install:

uninstall:

clean:
	rm -rf a.out

dvi:

dist:

tests:

gcov_report:

git:
	git add .
	git commit -m "$(date)"
	git push

